### ISSUE TITLE
how to test an image

### ISSUE THREAD

**Issue by IamMegatron2025** [johannesu/cnn-cells#5]
hello, I am interesting at your this repository. Now I want to do a simple test for a image. But how to save and load trained model in your `main` file?  can you give some advice~
thank you in advance

**Comment by johannesu** [comment]
Sorry for the late reply.

You can follow the instructions in:
https://www.quora.com/How-do-I-save-a-convolution-neural-network-model-after-training-I-am-working-in-Python
